gvwilson/mossball

GRADING.md

Created grading scheme for Jan-Apr 2025

---

cassandratin13/cassandra_demo.py
cassandratin13/index.css
cassandratin13/index.js

Create a minimal plugin - Cassandra

---

Barsamyan-D/README.md
Barsamyan-D/demo_notebook.py
Barsamyan-D/index.css
Barsamyan-D/index.js
Barsamyan-D/requirements.txt

Closes #2
Created a Marimo notebook with custom scatter plot and a counter plugin.

Create a minimal plugin - David

---

Barsamyan-D/str-strip-plugin-david/StructureStripWidget.py
Barsamyan-D/str-strip-plugin-david/structure_strip.py
cassandratin13/sort_paragraphs_plugin/SortTheParagraphs.py
cassandratin13/sort_paragraphs_plugin/sort_paragraphs.py
design-system/global.css
eun-chae-s/drag-the-words/implementation/DragWordsWidget.py
eun-chae-s/drag-the-words/implementation/drag_the_words.py
evence_wang/FileUploaderModule/FileUploader.py
lorena-b/find-the-words/demo.py
lorena-b/find-the-words/src/find_the_words/__init__.py

- allow widgets to read from the global.css file to use common styles

Configure widgets for global css

---

lorena-b/find-the-words/js/icons.js
lorena-b/find-the-words/js/widget.css
lorena-b/find-the-words/js/widget.js

Add feedback styles for find the words

---

eun-chae-s/drag-the-words/implementation/drag_the_words.css

Updated the border styling for the drag the words to be consistent with other components

Frontend border

---

cassandratin13/mcq_plugin/MCQPlugin.py
cassandratin13/mcq_plugin/mcq.css
cassandratin13/mcq_plugin/mcq.js
cassandratin13/mcq_plugin/mcq_plugin.py
cassandratin13/sort_paragraphs_plugin/stp.css

Add mcq styling

---

eun-chae-s/drag-the-words/implementation/drag_the_words.js

https://github.com/user-attachments/assets/91a6d652-93d1-4c34-a344-d2094406d5a5
Added an enhancement for the drag the words
- Reset button to make all the answer boxes blank
- X-mark icon next to each text in the answer box to be able to remove locally

Add reset button and remove answer icon button

---

.github/workflows/python-app.yml

Create workflow for running tests

---

pyproject.toml
tests/conftest.py
tests/notebooks/file_uploader_test.py
tests/testfiles/test_file_uploader.py
tests/testfiles/test_find_the_words.py

closes #63 
- mock s3 instance in the notebook
- check that create, upload, and delete functionalities work in the ui

add browser tests for file uploader plugin

---

CONTRIBUTING.md

add testing instruction to contributing file

---

lorena-b/find-the-words/README.md
lorena-b/find-the-words/demo.py

Update README.md for find the words

---

CONTRIBUTING.md

Add setup notes and information for find the words plugin

---

Barsamyan-D/str-strip-plugin-david/str.js
tests/conftest.py
tests/notebooks/structure_strip_test.py
tests/testfiles/test_structure_strip.py

Closes #62
- Implemented Selenium tests for the structure strip widget.
- Also made small changes to the Copy feature to fix bug.

Tests for structure strip

---

frontend/widgets.py
frontend/widgets_notebook_local.py
lorena-b/find-the-words/demo.py
lorena-b/find-the-words/js/constants.js
lorena-b/find-the-words/js/grid.js
lorena-b/find-the-words/js/icons.js
lorena-b/find-the-words/js/timer.js
lorena-b/find-the-words/js/widget.css
lorena-b/find-the-words/js/widget.js
lorena-b/find-the-words/src/find_the_words/__init__.py

- improve input validation
- improve word selection handling to not select substrings of a larger word if the substring is a word in the word bank
- apply formating to the files

find the words bug fixes and improvements

---

frontend/widgets_notebook_local.py

Closes #91
Change colour theme back to regular blue/grey for local notebook demo.

Change back to regular colour theme for demo

---

README.md

add demo video link

---

CONTRIBUTING.md
eun-chae-s/drag-the-words/implementation/README.md
eun-chae-s/drag-the-words/implementation/drag_the_words.py

Add instructions for Drag the Words + Update the plugin python file to correctly import the libraries

---

CONTRIBUTING.md

Closes #88. Added styling documentation to CONTRIBUTING.md.

Add styling contributing documentation

---

CONTRIBUTING.md

Add tools/resources that are useful for development, etc.
closes #80

add resources
